DB: 'Server=product-catalog-non-prod.cs60zg0gg0au.us-east-1.rds.amazonaws.com,1433;User Id=sa; Password=PTsDJHExMYZQEtaUhgBmtY2; Initial Catalog=ProductCatalogDev;Integrated Security=false;MultipleActiveResultSets=True;Persist Security Info=True;'
FameConfig__Cache__InstanceName: ProdCatDev
FameConfig__Cache__Port: 6379
FameConfig__Cache__Server: spree-non-prod.qovact.0001.use1.cache.amazonaws.com
APIGW_CNAME: product-renders-fallback-dev.fameandgroups.com
CLOUDFRONT_CNAME: product-renders-qa4.fameandgroups.com
Dropbox: opL9ZipjKSAAAAAAAAAC9Hzvlkv-YrSn4QKJUxuiQWlstSEmkEP-HUvYB9-3swyT
