name: CloudFormationDeploy
on: 
  push:
    branches:
    - qa4
    - develop
    - master

jobs:
  build:
    name: Go
    runs-on: ubuntu-latest
    steps:  
      - uses: fameandpartners/checkout@7f0669ca1fd955c0e0fd85ee8d5b8d16978be97e
      - uses: fameandpartners/ServerlessDeployAction@master
        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          PACKAGE_DIR: ./Fame.ImageGenerator
